version: '3.2'

services:
  resurface:
    image: docker.resurface.io/release/pilot
    container_name: hackernews_resurface
    ports:
      - '4000:4000'
      - '4001:4001'
      - '4002:4002'

  hackernews:
    image: test-flask-hackernews:latest
    container_name: hackernews
    command: gunicorn --bind :5000 wsgi:application
    ports: ['80:5000']
    env_file:
      - .env
