version: '3'

services:
  hackernews:
    container_name: hackernews_flask
    build: .
    command: gunicorn --bind :5000 wsgi:application
    ports: ['80:5000']
    volumes: ['.:/app']
    restart: always
    env_file:
      - .env
